Update rancher pull-scripts rule
chainguard-dev/malcontent pull request #528
Opened 2024-10-17 14:49 UTC by egibs

This PR addresses the continued critical finding as seen in: https://github.com/wolfi-dev/os/pull/31009

The current test data was generated when this rule still applied so there weren't any refresh updates.

2024-10-17 20:04 UTC, tstromberg requested changes

2024-10-18 12:26 UTC, egibs commented on rules/false_positives/rancher.yara
> +    $downloading = "echo \"Downloading charts-build-scripts version ${CHARTS_BUILD_SCRIPTS_REPO}@${CHARTS_BUILD_SCRIPT_VERSION}\""
Updated in [`7d2c6b1` (#528)](https://github.com/chainguard-dev/malcontent/pull/528/commits/7d2c6b1556637a8cdd489855abb0de4eddcbf52d).

2024-10-18 12:34 UTC, tstromberg requested changes

2024-10-18 12:34 UTC, tstromberg commented on rules/false_positives/rancher.yara
> +    $version = "./bin/charts-build-scripts --version"
these last two rules duplicate $charts

2024-10-18 12:34 UTC, tstromberg commented on rules/false_positives/rancher.yara
> +    $charts = "charts-build-scripts"
consider adding `fullword` declaration so that this doesn't match zcharts-build-scripts

2024-10-18 12:34 UTC, tstromberg commented on rules/false_positives/rancher.yara
> +    $binary_name = "BINARY_NAME=charts-build-scripts"
I think this $binary_name rule should be sufficient - it's a superset of $charts.

2024-10-18 12:35 UTC, tstromberg commented
TL;DR: Let's start with simpler (yet still unlikely) overrides when possible.

2024-10-18 18:06 UTC, tstromberg approved these changes

2024-10-18 18:15 UTC, merged